[package]
name = "hq"
version = "0.1.0"
authors = ["ozbe <1372945+ozbe@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
cssparser = "0.25.9"
scraper = "0.11.0"
selectors = "0.21.0"
structopt = "0.3.12"